management:
  security:
    enabled: false
spring:
  application:
    name: microservice-provider-user 
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
    sql-script-encoding: UTF-8
    
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      indent-output: true
      write-dates-as-timestamps: true
    date-format: yyyy-MM-dd HH:mm:ss  
    
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE  


eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    metadata-map:
#      my-metadata: 我自定义的元数据

---
spring:
  profiles: user1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    
---
spring: 
  profiles: user2
server: 
  port: 8001
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true





