spring:  
  application:
    name: microservice-provider-movie-feign-hystrix-stream  
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
         
server:
  port: 8020


eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    
MICROSERVICE-PROVIDER-USER:
  ribbon: 
    NFLoadBalancerRuleClassName: con.netflix.loadbalancer.RandomRule


feign:
  client:
    config:
      MICROSERVICE-PROVIDER-USER: 
        loggerLevel: full
  hystrix: 
    enabled: true





